#ifndef	OFST_VERSION_INCLUDED
#define OFST_VERSION_INCLUDED

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define OFST_VERSION_MAJOR	1
#define OFST_VERSION_MINOR	0
#define OFST_VERSION_PATCH	0
#define OFST_VERSION_BETA	0
#define OFST_VERSION_VERSTRING	MAKE_STR(OFST_VERSION_MAJOR) "." MAKE_STR(OFST_VERSION_MINOR) "." MAKE_STR(OFST_VERSION_PATCH) "." MAKE_STR(OFST_VERSION_BETA)

#endif
